@Veneta.Recruitment.ConsumerService_HostAddress = http://localhost:5046


GET {{Veneta.Recruitment.ConsumerService_HostAddress}}/consumers
Accept: application/json

###
GET {{Veneta.Recruitment.ConsumerService_HostAddress}}/consumers/b6d09d51-8ce2-4d0b-a795-6e7cfb67567e
Accept: application/json

###

POST {{Veneta.Recruitment.ConsumerService_HostAddress}}/consumers
Accept: application/json
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "id": "b6d09d51-8ce2-4d0b-a795-6e7cfb67567e",
    "address": {
        "postalCode": "1111aa",
        "street": "example street",
        "houseNumber": "1a"
    },
    "firstName": "firstName",
    "lastName": "lastName"
}
###

PUT {{Veneta.Recruitment.ConsumerService_HostAddress}}/consumers/b6d09d51-8ce2-4d0b-a795-6e7cfb67567e
Accept: application/json
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "firstName": "firstName updated",
  "lastName": "lastName updated"
}
###

PUT {{Veneta.Recruitment.ConsumerService_HostAddress}}/consumers/b6d09d51-8ce2-4d0b-a795-6e7cfb67567e
Accept: application/json
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "address": {
    "postalCode": "2222aa",
    "street": "example street updated",
    "houseNumber": "1a updated"
  }
}
###